### ISSUE TITLE
Section names containing a Linebreak are garbled

### ISSUE THREAD

**Issue by robert-gdv** [ietf-tools/rfc2html#27]
The section head for [RFC7515, 4.1.8](https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.8) should read

> "x5t#S256" (X.509 Certificate SHA-256 Thumbprint) Header Parameter

Instead the word `Parameter` seems to overlay the first part of `"x5t#S256" (X.509 Certificate SHA-256 Thumbprint) Header`

Update to the document because of htmlization [issues are refused](https://www.rfc-editor.org/errata/eid6118). So the htmlization must be able to handle this header.

**Comment by larseggert** [comment]
This might be a browser issue?
Screenshot

**Comment by rjsparks** [comment]
Robert  - could you let us know what browser (and version) you were using when you saw the issue?

**Comment by robert-gdv** [comment]
I am using Microsoft Edge, Version 104.0.1293.70 (Offizielles Build) (64-Bit)

The same issue is with Chrome Version 104.0.5112.102 (Offizieller Build) (64-Bit)

Unfortunately, I can't upload images ("Something went really wrong").

**Comment by robert-gdv** [comment]
The issue seems to be the` line-height: 0pt;` CSS style for header. Without that, the lines are below each other.
Additionally, without it, the lines above and below the header take exact one line (like in txt view).

After trying out some values, the line height 0pt seems to be a nasty trick to reduce the vertical space before and after the headers.
Effectively, it tells the browser: "The header consumes no vertical space at all, let the empty line before and after touch each other directly".

That seems like a hack to me.

If you want to archive that effect, I suggest:

1. Remove empty lines before and after the header.
2. Put adjacent Header text in the same span element.
3. Modify the CSS for h1-h5, .h1-.h5:
3.1. Use display: block; instead of display: inline; for the header.
3.2. Remove line-height 0pt
3.3. Add margin: 0.8em 0; (or play around with margin-top and margin-bottom

**Comment by larseggert** [comment]
@rjsparks where is that CSS coming from? It's not part of `rfc2html`.

**Comment by rjsparks** [comment]
I don't know where it's coming from for the rfc-editor website - I will ask.
For the datatracker, it lives here: 
https://github.com/ietf-tools/datatracker/blob/main/ietf/templates/doc/htmlized_base.html#L51
Note that we had already commented out that particular directive.

**Comment by larseggert** [comment]
We should start migrating to a canonical CSS here.

**Comment by rjsparks** [comment]
In the meantime, the rfc-editor indicates that they have updated their css. Please confirm whether it helps?

**Comment by larseggert** [comment]
Is their css online somewhere?

**Comment by robert-gdv** [comment]
It works! Thanks
